
import javax.swing.JButton;
import javax.swing.JOptionPane;



class node{
    private int data;
    private node left;
    private node right;
    private int xdeğeri;
    private int ydeğer;

    public node(int data, int xdeğeri, int ydeğer) {
        this.data = data;
        this.xdeğeri = xdeğeri;
        this.ydeğer = ydeğer;
        this.left=null;
        this.right=null;
    }

    public int getXdeğeri() {
        return xdeğeri;
    }

    public void setXdeğeri(int xdeğeri) {
        this.xdeğeri = xdeğeri;
    }

    public int getYdeğer() {
        return ydeğer;
    }

    public void setYdeğer(int ydeğer) {
        this.ydeğer = ydeğer;
    }



    public int getData() {
        return data;
    }

    public void setData(int data) {
        this.data = data;
    }

    public node getLeft() {
        return left;
    }

    public void setLeft(node left) {
        this.left = left;
    }

    public node getRight() {
        return right;
    }

    public void setRight(node right) {
        this.right = right;
    }
    
    
}



public class NewJFrame1 extends javax.swing.JFrame {
    JButton dügümler_Dizisi[]=new JButton[100];
    node kok=new node(1,300,50);
    int eleman_sayisi=0;
    public NewJFrame1() {
        initComponents(); 
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        ekle = new javax.swing.JButton();
        deger = new javax.swing.JTextField();
        sırala = new javax.swing.JButton();
        yaz = new javax.swing.JTextField();
        derece = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        es = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl.setBackground(new java.awt.Color(0, 102, 102));

        ekle.setText("ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        sırala.setText("sırala");
        sırala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sıralaActionPerformed(evt);
            }
        });

        derece.setText("derece");
        derece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dereceActionPerformed(evt);
            }
        });

        jButton1.setText("arama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        es.setText("eleman sayısı");
        es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yaz)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sırala)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addComponent(derece)
                                .addGap(67, 67, 67)
                                .addComponent(es)))
                        .addGap(0, 292, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deger)
                    .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(derece)
                    .addComponent(jButton1)
                    .addComponent(es))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekle)
                    .addComponent(sırala))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        if(eleman_sayisi==0)
        {
        kok.setData(Integer.valueOf(deger.getText()));
        JButton kokbtn=new JButton(String.valueOf(kok.getData()));
        kokbtn.setLocation(kok.getXdeğeri(), kok.getYdeğer());
        kokbtn.setSize(50,30);
        pnl.add(kokbtn);
        dügümler_Dizisi[0]=kokbtn;eleman_sayisi++;
        repaint();
        }
        else
        {
             addNode(kok,Integer.valueOf(deger.getText()));
        }
       

    }//GEN-LAST:event_ekleActionPerformed

    private void sıralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sıralaActionPerformed
        if(eleman_sayisi==0)
        {
            JOptionPane.showMessageDialog(this,"Eleman olmadıgından sıralanamaz...");
        }
        else
        {
             transverseprint(kok);
        }
       
    }//GEN-LAST:event_sıralaActionPerformed

    private void dereceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dereceActionPerformed
        
        if(eleman_sayisi==0)
        {
               JOptionPane.showMessageDialog(this," Ağacta eleman yoktur");
        }
        else
        {
               JOptionPane.showMessageDialog(this, String.valueOf(Height(kok))+" Ağacın Derecesidir");
        }
             
    }//GEN-LAST:event_dereceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(eleman_sayisi==0)
     {
         JOptionPane.showConfirmDialog(this,"Ağaçta henüz eleman yoktur.");
     }
     else
     {
     if(search(kok,Integer.valueOf(deger.getText())))
     {
         JOptionPane.showConfirmDialog(this,"Değer ağaçta bulunuyor...");
     }
     else
     {
         JOptionPane.showConfirmDialog(this,"Değer ağaçta bulunmuyor...");
     }
     }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esActionPerformed
     JOptionPane.showMessageDialog(this,String.valueOf(getsize(kok))+" Eleman bulunuyor.");
    }//GEN-LAST:event_esActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deger;
    private javax.swing.JButton derece;
    private javax.swing.JButton ekle;
    private javax.swing.JButton es;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnl;
    private javax.swing.JButton sırala;
    private javax.swing.JTextField yaz;
    // End of variables declaration//GEN-END:variables

        public void addNode(node n,int value)
    {
        
        if(value>n.getData())
        {
            if(n.getRight()==null)
            {
                
                n.setRight(new node(value,n.getXdeğeri()+100,n.getYdeğer()+40));
                dügümler_Dizisi[eleman_sayisi]=new JButton(String.valueOf(n.getRight().getData()));
                dügümler_Dizisi[eleman_sayisi].setLocation(n.getRight().getXdeğeri(),n.getRight().getYdeğer());
                dügümler_Dizisi[eleman_sayisi].setSize(50,30);
                pnl.add(dügümler_Dizisi[eleman_sayisi]);
                eleman_sayisi++;
                repaint();
                
                
                
            }
            else
            {
                addNode(n.getRight(),value);
            }
        }
        else if(value<n.getData())
        {
             if(n.getLeft()==null)
            {
                
                n.setLeft(new node(value,n.getXdeğeri()-100,n.getYdeğer()+40));
                dügümler_Dizisi[eleman_sayisi]=new JButton(String.valueOf(n.getLeft().getData()));
                dügümler_Dizisi[eleman_sayisi].setLocation(n.getLeft().getXdeğeri(),n.getLeft().getYdeğer());
                dügümler_Dizisi[eleman_sayisi].setSize(50,30);
                pnl.add(dügümler_Dizisi[eleman_sayisi]);
                eleman_sayisi++;
                repaint();
            
            }
            else
            {
                addNode(n.getLeft(),value);
            }
        }
    }

    public void transverseprint(node n)
    {
        if(n!=null)
        {
            transverseprint(n.getLeft());
            yaz.setText(yaz.getText()+(" "+n.getData()+" "));
            transverseprint(n.getRight());
        }
    }

        public int Height(node kok)
    {
        if(kok==null)
        {
            return 0;
        }
        else
        {
            return Math.max(Height(kok.getLeft()),Height(kok.getRight()))+1;
        }
    }
    public boolean search(node n,int value)
    {
        if(n!=null)
        {
            if(n.getData()==value)
            {
                return true;
            }
            else
            {
                return search(n.getLeft(),value) || search(n.getRight(), value);
            }
        }
        return false;
    }

    private int getsize(node kok) {
        
        return eleman_sayisi;
    }


}
